version: '3.8'

services:
  db:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_DB: agaply
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1909
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: agaply
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/agaply
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1909
    depends_on:
      - db

volumes:
  pgdata: